name: shiori
description: A Database app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.4.5+65

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  darq: ^1.2.1
  device_info_plus: ^4.0.0
  devicelocale: ^0.5.4
  enum_to_string: ^2.0.1
  fl_chart: ^0.55.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_colorpicker: ^1.0.3
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.9
  flutter_native_timezone: ^2.0.0
  flutter_slidable: 1.3.0
  flutter_user_agentx: ^1.2.4
  fluttertoast: ^8.0.9
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  image_gallery_saver: ^1.7.1
  infinite_listview: ^1.1.0
  internet_connection_checker: ^0.0.1+3
  json_annotation: ^4.4.0
  linked_scroll_controller: ^0.2.0
  logger: ^1.1.0
  package_info_plus: ^1.4.2
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^10.0.0
  pull_to_refresh: ^2.0.0
  purchases_flutter: ^3.10.0
  rate_my_app: ^1.1.2
  responsive_builder: ^0.4.2
  responsive_grid: ^2.1.0
  screenshot: ^1.2.3
  shared_preferences: ^2.0.15
  sprintf: ^6.0.0
  synchronized: ^3.0.0+2
  transparent_image: 2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.1.4
  version_tracker: ^2.1.1
  waterfall_flow: ^3.0.2
  webview_windows: 0.1.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^8.5.0
  build_runner:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  hive_generator: ^1.1.3
  json_serializable: ^6.1.3
  lint: ^1.7.2
  mockito: ^5.0.16
  msix: ^3.6.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/artifacts/
    - assets/characters/
    - assets/characters_full/
    - assets/elements/
    - assets/furniture/
    - assets/gadgets/
    - assets/i18n/
    - assets/items/common/
    - assets/items/currency/
    - assets/items/elemental/
    - assets/items/experience/
    - assets/items/ingredients/
    - assets/items/jewels/
    - assets/items/local/
    - assets/items/others/
    - assets/items/talents/
    - assets/items/weapon/
    - assets/items/weapon_primary/
    - assets/monsters/
    - assets/others/
    - assets/skills/
    - assets/weapons/
    - assets/weapons/bows/
    - assets/weapons/catalysts/
    - assets/weapons/polearms/
    - assets/weapons/claymores/
    - assets/weapons/swords/
    - assets/icon/icon.png

  fonts:
    - family: Shiori
      fonts:
        - asset: assets/fonts/Shiori.ttf

flutter_intl:
  enabled: true

msix_config:
  display_name: "Shiori for Genshin: Unofficial"
  publisher_display_name: MiraiSoft
  identity_name: 52493MiraiSoft.ShioriforGenshinUnofficial
  publisher: CN=58BF90DC-3D34-433E-A12B-4C504DF78641
  logo_path: assets\icon\icon.png
  languages: en
  capabilities: 'internetClient'
  store: true
