name: flutter_tests
on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create secrets file
        run: |
          echo "class Secrets { static String appCenterKey = '1234'; static String androidPurchasesKey = '1234'; }" > lib/infrastructure/secrets.dart

      - name: Install and set flutter version
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '2.10.2'
          
      - name: Generate localization files
        run: |
          flutter pub add intl_utils
          flutter pub run intl_utils:generate

      - name: Restore packages
        run: flutter pub get
          
      - name: Run build_runner build
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: Run tests
        run: flutter test --coverage
